### PR TITLE
testing books in aws s3 bucket by reading their json files

### PR DESCRIPTION
**Pull request by omehes**
verifying that json files of books are in s3 bucket and have content present.

### CODE REVIEW

**Comment by omehes** [comment]
@c0ldcalamari that 1 file is not due to my changes, it happend yesterday too. Mike re-run the tests and it was gone. Weird issue... not related

**Comment by omehes** [comment]
@c0ldcalamari I am re-working this test, so I will close this PR and open another one and assign it to you for your review. Coming soon

**Comment by m1yag1** [comment]
What's the purpose of these tests?

**Comment by omehes** [comment]
@m1yag1 @c0ldcalamari I redone the test. It now checks all the books, skips those which are not in the s3 bucket and checks json file of those 4 which in the bucket uploaded by you. 

I am checking that book url has status code 200, that slug names of chapters which are in every book are there (preface and index), to make sure that the json file has correct content and that the title of the jason file is the expected title of the corresponding book.

**Comment by c0ldcalamari** [comment]
@omehes how do i review this PR?

**Comment by omehes** [comment]
@c0ldcalamari I am not sure how @m1yag1 is doing it. Maybe Mike can advice?

**Comment by brittweinstein** [comment]
@c0ldcalamari please see the readme on cnx automation

**Comment by c0ldcalamari** [comment]
Tested by running: 
` pytest -k test_all_cops_books.py --s3_base_url https://d2vp2c5n7jbofk.cloudfront.net --headless`

which returned:
```
==================================================================================================================================== warnings summary =====================================================================================================================================
/Users/brenda/.pyenv/versions/3.7.4/envs/cnx-automation/lib/python3.7/site-packages/_pytest/mark/structures.py:327
  /Users/brenda/.pyenv/versions/3.7.4/envs/cnx-automation/lib/python3.7/site-packages/_pytest/mark/structures.py:327: PytestUnknownMarkWarning: Unknown pytest.mark.testrail - is this a typo?  You can register custom marks to avoid this warning - for details, see https://docs.pytest.org/en/latest/mark.html
    PytestUnknownMarkWarning,

-- Docs: https://docs.pytest.org/en/latest/warnings.html
------------------------------------------------------------------------------------------------ generated html file: file:///Users/brenda/Projects/00_openstax/cnx-automation/report.html ------------------------------------------------------------------------------------------------
========================================================================================================= 4 passed, 40 skipped, 58069 deselected, 1 warning in 105.54s (0:01:45) ==========================================================================================================
```

Which shows the appropriate books were found in the s3 bucket as expected.

**Pull request merged**
