### PR TITLE
Add test data for rex load tests

### PR DESCRIPTION
**Pull request by BryanEliDimas**
1K randomly picked URLs.

### CODE REVIEW

**Comment by BryanEliDimas** [comment]
Seems like technically I could just merge this one myself but requested review from Mulich and Mike.

**Comment by pumazi** [comment]
How about we change the filename? These are cnx urls as opposed urls for the rex site.

**Comment by BryanEliDimas** [comment]
Sure. Done. @pumazi

**Comment by pumazi** [comment]
Sorry, you need to rename it in the artillery config as well, no?

**Comment by BryanEliDimas** [comment]
Ah, true! Done. @pumazi

**Comment by pumazi** [comment]
None of the test failures seem to be related to this change.

**Comment by BryanEliDimas** [comment]
It's 7 or 8 webview tests that are failing. I've restarted them. @m1yag1 I

**Pull request merged**
