### PR TITLE
WIP Neb publish tests

### PR DESCRIPTION
**Pull request by Dantemss**
- C195247
- C195243

Based on https://github.com/openstax/cnx-automation/pull/129, will rebase after that is merged for a smaller diff.

### CODE REVIEW

**Comment by kerwinso** [comment]
Batch regression tests live here: https://openstax.testrail.com/index.php?/suites/view/70&group_by=cases:section_id&group_order=asc&group_id=13032
Some will be difficult to automate.

**Comment by pumazi** [comment]
I didn't know this changeset existed. I was expecting it was already merged. I'll likely be reviving this work very soon.

**Comment by m1yag1** [comment]
@omehes this changeset should be useful for you. this is some blocked work @Dantemss was working on for publishing.

**Comment by pumazi** [comment]
This was partially merged in https://github.com/openstax/cnx-automation/pull/129. I'll rebase a portion of this and open a new pull request.

**Pull request closed without merging**
