### PR TITLE
Adjusted Show more/less assertions

### PR DESCRIPTION
**Pull request by omehes**
simplified the failing assertions for Show less/more links

### CODE REVIEW

**Comment by rnathuji** [comment]
@omehes - I may be mistaken, but I think this PR inadvertently includes some changes you removed from [PR 710](http://github.com/openstax/cnx-automation/pull/710/). Perhaps this PR was only meant to include [this commit](https://github.com/openstax/cnx-automation/pull/711/commits/5003e20d83d9b34fc1b790ebf3b917d4a9df4609)?

**Comment by omehes** [comment]
@rnathuji yes, it should have been only the more/less changes. Not sure why it includes the other commit it too. I might have created that branch not from master but from the branch containing the commit for facebook, twitter and linkedin changes. But this should still be ok to merge, no?

**Comment by rnathuji** [comment]
Oh, my mistake. I thought you had altered the previous commit but it looks like you added a new commit when you made the social link changes. Yeah, this will merge fine.

**Review by rnathuji — APPROVED** [review]

**Comment by omehes** [comment]
Thanks. I will have to watch though more closely where I base my branches from to avoid confusion...

**Pull request merged**
